default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['DEFAULT_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  
development:
  <<: *default
  database: ruffmailer_development
  
test:
  <<: *default
  database: ruffmailer_test
  
production:
  <<: *default
  database: ruffmailer_production
  username: ruffmailer
  password: <%= ENV['RUFFMAILER_DATABASE_PASSWORD'] %>